---
git_ref: master
user: vagrant
home_root: /home/vagrant
dotfiles_path: /home/vagrant/.DotFiles
dotvim_path: /home/vagrant/.vim

dev_yum_dependencies:
  - "@Development tools"
  - curl
  - git-core
  - vim
  - weechat
  - autojump
  - autojump-zsh
  - zsh
  - ack
  - tmux
  - golang
  - automake
  - pkgconfig
  - pcre-devel
  - zlib-devel
  - xz-devel

dev_apt_dependencies:
  - build-essential
  - curl
  - git-core
  - vim
  - weechat
  - autojump
  - zsh
  - ack
  - tmux
  - automake
  - pkg-config
  - libpcre3-dev
  - zlib1g-dev
  - liblzma-dev
