---
- name: Update APT cache
  apt: update_cache=yes

- name: Install APT Dev dependencies
  apt: pkg={{ item }}
  with_items:
    dev_apt_dependencies

- name: Add golang repository
  apt_repository: repo='ppa:gophers/go'

- name: Install GoLang
  apt: pkg=golang