- local_action: stat path={{ home_root }}/DotFiles
  sudo: false
  register: dotfiles_exists

- name: Debug result
  debug: var=dotfiles_exists

- name: Get DotFiles
  action: git
  sudo: false
  args:
    accept_hostkey: yes
    repo: git@github.com:vivienschilis/DotFiles.git
    dest: "{{ home_root }}/DotFiles"
    update: yes
    force: yes

- name: Setup DotFiles
  command: "make -C {{ home_root }}/DotFiles -f Makefile -k setup"
  args:
    chdir: "{{ home_root }}/DotFiles"
  when: not dotfiles_exists.stat.exists

- name: Update DotFiles
  command: "make -C {{ home_root }}/DotFiles -f Makefile -k update"
  args:
    chdir: "{{ home_root }}/DotFiles"
  when: dotfiles_exists.stat.exists