---
- action: stat path={{ dotfiles_path }}
  sudo: false
  register: dotfiles_exists

- name: Get DotFiles
  action: git
  sudo: false
  args:
    accept_hostkey: yes
    repo: https://github.com/vivienschilis/DotFiles.git
    dest: "{{ dotfiles_path }}"
    update: yes
    force: yes

- name: Setup DotFiles
  sudo: false
  command: "make -C {{ dotfiles_path }} -f Makefile -k setup"
  args:
    chdir: "{{ dotfiles_path }}"
  when: not dotfiles_exists.stat.exists

- name: Setup OhMyZsh
  sudo: false
  command: "make -C {{ dotfiles_path }} -f Makefile -k ohmyzsh"
  args:
    chdir: "{{ dotfiles_path }}"
  when: not dotfiles_exists.stat.exists

- name: Setup Vim
  sudo: false
  command: "make -C {{ dotfiles_path }} -f Makefile -k vim"
  args:
    chdir: "{{ dotfiles_path }}"
  when: not dotfiles_exists.stat.exists

- name: Update DotFiles
  sudo: false
  command: "make -C {{ dotfiles_path }} -f Makefile -k update"
  args:
    chdir: "{{ dotfiles_path }}"
  when: dotfiles_exists.stat.exists
