- local_action: stat path={{ dotvim_path }}
  sudo: false
  register: dotfiles_exists

- name: Get DotVim
  action: git
  sudo: false
  args:
    accept_hostkey: yes
    repo: git@github.com:vivienschilis/DotVim.git
    dest: "{{ dotvim_path }}"
    update: yes
    force: yes

- name: Setup DotVim
  command: "make -C {{ dotvim_path }} -f Makefile -k run"
  sudo: false
  args:
    chdir: "{{ dotvim_path }}"
  when: not dotfiles_exists.stat.exists

- name: Update DotVim
  command: "make -C {{ dotvim_path }} -f Makefile -k run"
  sudo: false
  args:
    chdir: "{{ dotvim_path }}"
  when: dotfiles_exists.stat.exists