- action: "stat path={{ dotvim_path }}/vimrc"
  sudo: false
  register: dotvim_exists

- name: Get DotVim
  action: git
  sudo: false
  args:
    accept_hostkey: yes
    repo: https://github.com/vivienschilis/DotVim.git
    dest: "{{ dotvim_path }}"
    update: yes
    force: yes

- name: Setup DotVim
  command: "make -C {{ dotvim_path }} -f Makefile -k run"
  sudo: false
  args:
    chdir: "{{ dotvim_path }}"
  when: not dotvim_exists.stat.exists

- name: Update DotVim
  command: "make -C {{ dotvim_path }} -f Makefile -k update"
  sudo: false
  args:
    chdir: "{{ dotvim_path }}"
  when: dotvim_exists.stat.exists