---
- name: Get DotVim
  action: git
  sudo: false
  args:
    accept_hostkey: yes
    repo: https://github.com/vivienschilis/DotVim.git
    dest: "{{ dotvim_path }}"
    update: yes
    force: yes

- name: Install DotVim
  command: "make -C {{ dotvim_path }} -f Makefile -k install"
  sudo: false
  args:
    chdir: "{{ dotvim_path }}"

- name: Install DotVim
  command: "make -C {{ dotvim_path }} -f Makefile -k run"
  sudo: false
  args:
    chdir: "{{ dotvim_path }}"
