- name: Download Golang.
  get_url: >
    url=http://golang.org/dl/go1.3.src.tar.gz
    dest=/tmp/go1.3.src.tar.gz

- name: Extract Golang.
  command: >
    tar -zxvf /tmp/go1.3.src.tar.gz
    chdir=/tmp
    creates=/tmp/go

- name: Build Golang.
  command: >
    {{ item }}
    chdir=/tmp/go/src
    creates=/usr/local/bin/go
  with_items:
    - ./all.bash
