- name: Update packages
  command: yum -y update

- yum: name="@Development tools" state=present
- yum: name=curl state=present
- yum: name=git-core state=present
- yum: name=vim state=present
- yum: name=weechat state=present
- yum: name=autojump state=present

- yum: name=zsh state=present
- yum: name=ack state=present
- yum: name=tmux state=present
- yum: name=golang state=present

- include: silver_searcher.yml
- include: dotvim.yml
- include: dotfiles.yml
- include: git-surf.yml
- include: zsh.yml
