---
- include: ssh_forwarding.yml

- name: Add github.com to known_hosts file
  lineinfile: dest=/home/{{ansible_ssh_user}}/.ssh/known_hosts
    line="{{ lookup('pipe', 'ssh-keyscan github.com') }}"
    state=present
    create=yes
    mode=0644

- name: Update packages
  command: yum -y update
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Amazon'

- name: Install YUM Dev dependencies
  yum: name="{{ item }}"
  with_items:
    dev_yum_dependencies
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Amazon'

- name: Update APT cache
  apt: update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install APT Dev dependencies
  apt: pkg={{ item }}
  with_items:
    dev_apt_dependencies
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: silver_searcher.yml
- include: dotvim.yml
- include: dotfiles.yml
- include: git-surf.yml
- include: zsh.yml
