# Run the equivalent of "apt-get update" as a separate step
- apt: update_cache=yes

- apt: name=build-essential state=present
- apt: name=curl state=present
- apt: name=git-core state=present
- apt: name=vim state=present
- apt: name=weechat state=present
- apt: name=autojump state=present

- apt: name=zsh state=present
- apt: name=ack state=present
- apt: name=tmux state=present

- include: silver_searcher.yml
- include: golang.yml
- include: dotfiles.yml
- include: dotvim.yml
- include: git-surf.yml

- name: Set zsh as default shell
  user: name={{ user }} shell=/bin/zsh