---
- include: ssh_forwarding.yml

- name: Add github.com to known_hosts file
  lineinfile: dest=/home/{{ansible_ssh_user}}/.ssh/known_hosts
    line="{{ lookup('pipe', 'ssh-keyscan github.com') }}"
    state=present
    create=yes
    mode=0644

- name: Apt dependencies
  include: yum_pkg.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Amazon'

- name: YUM dependencies
  include: apt_pkg.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: silver_searcher.yml
- include: dotfiles.yml
- include: git-surf.yml
- include: zsh.yml
- include: direnv.yml
