---
- name: Download Silver searcher
  action: git
  sudo: false
  args:
    accept_hostkey: yes
    repo: https://github.com/ggreer/the_silver_searcher.git
    dest: /tmp/the_silver_searcher
    update: yes
    force: yes

- name: Build Silver searcher
  command: ./build.sh
  args:
    chdir: /tmp/the_silver_searcher

- name: Build Silver searcher
  command: make install
  args:
    chdir: /tmp/the_silver_searcher