- name: make sure root can use SSH agent forwarding of default user
  lineinfile: dest=/etc/sudoers
              state=present
              regexp='^Defaults env_keep.*"SSH_AUTH_SOCK"$'
              line='Defaults env_keep += "SSH_AUTH_SOCK"'
